### ISSUE TITLE
hello, Jeepeng 貌似现在用不了呢？

### ISSUE THREAD

**Issue by plftzk** [Jeepeng/react-native-xinge-push#1]
在Android上测试，可以获取到deviceToken，但貌似没有在信鸽注册上，信鸽推送的内容也接收不到。

**Comment by Jeepeng** [comment]
如果能获取到deviceToken，证明已经在信鸽上注册成功了
至于失败的原因，可以开启debug模式`XGPush.enableDebug(true);`然后控制台`react-native log-android`看看日志有什么报错信息，具体可以去看官方文档：[推送失败原因](http://developer.qq.com/wiki/xg/%E7%83%AD%E9%97%A8%E9%97%AE%E9%A2%98%E4%B8%8E%E8%A7%A3%E7%AD%94/%E6%8E%A8%E9%80%81%E5%A4%B1%E8%B4%A5%E5%8E%9F%E5%9B%A0/%E6%8E%A8%E9%80%81%E5%A4%B1%E8%B4%A5%E5%8E%9F%E5%9B%A0.html)
