### ISSUE TITLE
求完整demo

### ISSUE THREAD

**Issue by fgxls** [Jeepeng/react-native-xinge-push#11]
哥们 可不可以给个完整的demo 比如react-native 的js里面怎么写，ios的delegate怎么写 现在这个有各种问题呀

**Comment by fgxls** [comment]
主要我XGPushTokenManager用不了，连start都不行，js里写没反应，delegate里写报错

**Comment by Jeepeng** [comment]
之前更新信鸽iOS SDK，不小心把没完成的代码提交了，现在好了  
具体demo请参考：[example](https://github.com/Jeepeng/react-native-xinge-push/blob/master/example)
