### ISSUE TITLE
manifest合并失败

### ISSUE THREAD

**Issue by fgxls** [Jeepeng/react-native-xinge-push#13]
请问我该编译成什么版本 试来试去都是这个问题

**Comment by Jeepeng** [comment]
报错信息贴出来看看

**Comment by fgxls** [comment]
Execution failed for task ':app:processDebugManifest'.
Manifest merger failed with multiple errors,see logs

**Comment by fgxls** [comment]
Execution failed for task ':app:processDebugManifest'.
Manifest merger failed with multiple errors,see logs

**Comment by Jeepeng** [comment]
信息不足，麻烦打开`Gradle Console`这个选项卡看一下具体的报错日志

**Comment by Jeepeng** [comment]
请在你的 `AndroidManifest.xml` 配置 `tools:replace="android:allowBackup`
参考： [example例子](https://github.com/Jeepeng/react-native-xinge-push/blob/master/example/android/app/src/main/AndroidManifest.xml#L14)
