### ISSUE TITLE
当调用 register 方法时 app 自动退出

### ISSUE THREAD

**Issue by stevenxyj** [Jeepeng/react-native-xinge-push#2]
当调用 register 方法时 app 自动退出
XGPush.register('jeepeng')

**Comment by Jeepeng** [comment]
能否提供以下信息：
react-native版本:  
react-native-xinge-push版本:
报错信息:

**Comment by stevenxyj** [comment]
"react": "16.0.0-alpha.12",
    "react-native": "0.47.1",
    "react-native-xinge-push": "^0.2.2"

xinge-push 我已经按照 Remove overriden createJSModules 和 Fixed issue when account = null 做过修改。

不上网时调用 XGPush.register('jeepeng') 不会退出。
联网时调用就会退出，没有错误信息。

**Comment by Jeepeng** [comment]
react-native 0.47及更高版本应该使用v0.3.0版本
另外确保`AndroidManifest.xml`里的相应配置换成自己的包名、AccessId和AccessKey
运行以下命令看一下日志(真机需连接数据线)：
ios: `react-native log-ios`
android: `react-native log-android`

**Comment by stevenxyj** [comment]
AccessId和AccessKey 都是对的，也是真机测试
已经升级到 v0.30 

AndroidManifest.xml 增加下面的一段就退出了，移队就可以启动。

  
  
  <receiver android:name="com.qq.xgdemo.receiver.MessageReceiver"
      android:exported="true" >
      <intent-filter>
          
          <action android:name="com.tencent.android.tpush.action.PUSH_MESSAGE" />
          
          <action android:name="com.tencent.android.tpush.action.FEEDBACK" />
      </intent-filter>
  </receiver>


只需要 中间的 com.qq.xgdemo 改我的 app 包名？还是需要怎么改

**Comment by Jeepeng** [comment]
改成`com.jeepeng.react.xgpush`
```
<receiver android:name="com.jeepeng.react.xgpush.receiver.MessageReceiver"
            android:exported="true" >
            <intent-filter>
                <!-- 接收消息透传 -->
                <action android:name="com.tencent.android.tpush.action.PUSH_MESSAGE" />
                <!-- 监听注册、反注册、设置/删除标签、通知被点击等处理结果 -->
                <action android:name="com.tencent.android.tpush.action.FEEDBACK" />
            </intent-filter>
        </receiver>
```

**Comment by stevenxyj** [comment]
可以，建议文档补充一下，尤其 ios 上的。
增加库， Build Phases->Link Binary With Libraries.
libz.tbd
CoreTelephony.framework

增加路径 Build Settings->Search Paths->Headers Search Paths.
$(SRCROOT)/../node_modules/react-native-xinge-push/ios

**Comment by Jeepeng** [comment]
好的，谢谢了，有空我去完善一下文档
