### ISSUE TITLE
android集成不成功

### ISSUE THREAD

**Issue by Wizhiai** [Jeepeng/react-native-xinge-push#20]
android集成是否是先按照官方文档集成，然后再link xinge-push？
但是我这样做以后在registerPush步骤报错：
XGPushManager.register.rgisterPush got 3 arguments expected 2
如果直接install xinge-push然后再link连推送都收不到。

求教android集成的大概思路。谢谢！ @Jeepeng

**Comment by Jeepeng** [comment]
请参考 https://github.com/Jeepeng/react-native-xinge-push/tree/master/example/android

**Comment by Wizhiai** [comment]
按照你的demo配置的跑起来在 XGPush.register('jeepeng').then(result => {
                // do something
            })
            .catch(err => {
                console.log(err);
            });
    }
这一步报错：XGPushManager.register.rgisterPush got 3 arguments expected 2
请问是否是这个参数原因呢？ @Jeepeng

**Comment by Jeepeng** [comment]
是 v0.7 版本吗

**Comment by Wizhiai** [comment]
v0.6,0.7提示还没更新把 @Jeepeng

**Comment by Wizhiai** [comment]
@@static register(account) {
    if (Platform.OS === 'ios') {
      !!account && XGPushManager.bindWithAccount(account);
      return XGPushManager.requestPermissions({
        alert: true,
        badge: true,
        sound: true
      });
    } else {
   //   return XGPushManager.registerPush(account);
  return XGPushManager.registerPush();
    }
  }
我把这个方法改了去掉一个参数就可以了，但是目前测试，可以正常收到推送了，只是在rn里用你的方法点击 this._getInitialNotification()ts
        this._getApplicationIconBadgeNumber()收到通知alert显示为{}，角标获取也一直为0， @Jeepeng

**Comment by Jeepeng** [comment]
最新版本是 0.7，已经修复这个问题；
`getInitialNotification()` 在 debug 模式下打包正常，release 打包后有问题，目前在查找原因中。。。
`XGPush.setApplicationIconBadgeNumber(99)`之后`getApplicationIconBadgeNumber`还是0吗

**Comment by Wizhiai** [comment]
角标正常了，我发现 android 有这个提示：Calling JS function after bridge has been destroyed: RCTDeviceEventEmitter.emit(["remoteNotificationsRegistered",{"deviceTo
然后这边rn监听不到
还有个错误：getPushInfo Error, otherPushImplClassName is null @Jeepeng

**Comment by Wizhiai** [comment]
解决了，我自己用 DeviceEventEmitter.addListener监听到了
