### ISSUE TITLE
小米，华为，魅族有第三方通道可以用吗？ 测试都不行

### ISSUE THREAD

**Issue by hzl3705** [Jeepeng/react-native-xinge-push#27]

**Comment by charmtiger** [comment]
最近小米和魅族没有测试，华为是正常的，你也要检查一下服务端推送是否成功，基本的配置是否有误。

**Comment by hzl3705** [comment]
我在信鸽那边开启小米的厂商推送通道之后，用官网的创建通知栏消息，输入token单推，显示在线设备1，到达设备0，打开APP也收不到推送了。
在关闭小米厂商推送通道之后，原先打开APP能收到推送，现在也收不到，到达设备依然是 0 ，这是什么原因呢 ？

我react-native是0.55.4版本 SDK是23，跟SDK有没有关系呢？

感谢回答。
