### ISSUE TITLE
是否可以支持最新的sdk

### ISSUE THREAD

**Issue by dany1** [Jeepeng/react-native-xinge-push#7]
1.ios是否可以支持3.x
2.android是否可以支持信鸽V3.2.2，华为小米魅族通道

**Comment by hwangjr** [comment]
@Jeepeng  什么时候支持 ios 3.x 版本呢？ 目前我打算使用这个项目，但是 ios 还未升级到最新。

**Comment by hwangjr** [comment]
@Jeepeng  好的，我先集成测试下。感谢。

**Comment by hwangjr** [comment]
@Jeepeng 能否将你的修改分支提交上来，这样我也可以提交merge request 给你。
