### ISSUE TITLE
最新版sdk出非常重要的功能了，什么时候更新一下

### ISSUE THREAD

**Issue by yunuo-tech** [Jeepeng/react-native-xinge-push#8]
最新版的 sdk 新增小米 魅族 华为的官方推送，什么时候抽空更新下吧

**Comment by charmtiger** [comment]
表示非常关注

**Comment by Jeepeng** [comment]
抱歉，最近工作很忙，我看看这个周末有没有时间更新一下，谢谢大家支持

**Comment by charmtiger** [comment]
@Jeepeng  非常感谢

**Comment by musicode** [comment]
小米推送啥时候更新啊

**Comment by charmtiger** [comment]
日常签到 表示关注

**Comment by musicode** [comment]
@Jeepeng 求 发新版

**Comment by musicode** [comment]
最新集成的小米和魅族能发新版，并给一份文档吗

**Comment by Jeepeng** [comment]
@musicode 还没有测试，等待小米开发者审核中。。。不过我可以先发一版，有问题欢迎反馈

**Comment by musicode** [comment]
我看 readme 把安卓的配置都删掉了，是否那些都不需要了呢

**Comment by Jeepeng** [comment]
@musicode 不需要了，根据官方文档，AndroidStudio会自动集成

**Comment by musicode** [comment]
包括配置权限都会自动集成了，好方便啊

**Comment by musicode** [comment]
@Jeepeng example/android 目录最近没有更新，最新版还是参考它么

**Comment by Jeepeng** [comment]
@musicode 是的，参考`example`

**Comment by musicode** [comment]
example 是 9 个月前的，那时候还没有集成华为，小米，而且 AndroidManifest.xml 还配置了好多权限，确定是参考它吗

**Comment by Jeepeng** [comment]
@musicode 我这边显示2天前 [example](https://github.com/Jeepeng/react-native-xinge-push/tree/master/example)

**Comment by musicode** [comment]
@Jeepeng example 无法运行
![image](https://user-images.githubusercontent.com/2732303/37865413-09dae98e-2fb7-11e8-99bc-edefe863143a.png)

我按照 example 集成到项目里

```js
XGPush.init(PUSH_ACCESS_ID, PUSH_ACCESS_KEY)
XGPush.register(id)
```

之后并没有触发 `register` 事件，请问一下应该怎么调试呢
